name: explorePy37
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.0.2o
  - pip=10.0.1
  - python=3.7.0
  - readline=7.0
  - setuptools=39.2.0
  - sqlite=3.24.0
  - tk=8.6.7
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
